import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import ScrollToTopButton from "@/components/ScrollToTopButton";
import ScrollActionButtons from "@/components/ScrollActionButtons";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <CommentsProvider> */}
        {children}
        {/* Plugin Script */}
        <Script
          src="https://mantracollab-cdns.s3.ca-central-1.amazonaws.com/comment-widget.min.js"
          strategy="afterInteractive"
        />
        <Nav />
        <ScrollToTopButton />
        <ScrollActionButtons />
        {/* <CommentOverlay /> */}
        {/* </CommentsProvider> */}
      </body>
    </html>
  );
}
